//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsLite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmsLite.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action {0} does not have a CmsPageTemplate attribute..
        /// </summary>
        public static string ActionDoesNotHaveCmsPageTemplateAttribute {
            get {
                return ResourceManager.GetString("ActionDoesNotHaveCmsPageTemplateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action with the name {0} does not exist..
        /// </summary>
        public static string ActionNotFound {
            get {
                return ResourceManager.GetString("ActionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller {0} does not have a CmsSectionTemplate attribute..
        /// </summary>
        public static string ControllerDoesNotHaveCmsSectionTempalteAttribute {
            get {
                return ResourceManager.GetString("ControllerDoesNotHaveCmsSectionTempalteAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controller with the name {0} does not exist..
        /// </summary>
        public static string ControllerNotFound {
            get {
                return ResourceManager.GetString("ControllerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email {0} is already in user by another user..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Model type {0} was not found. Cms Models must implement the ICmsModel interface..
        /// </summary>
        public static string ModelTypeNotFound {
            get {
                return ResourceManager.GetString("ModelTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Cms Section Templates were found. You must create at least one controller, and mark it using the CmsSectionTemplate attribute..
        /// </summary>
        public static string NoCmsSectionTemplatesFound {
            get {
                return ResourceManager.GetString("NoCmsSectionTemplatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Node cannot be null..
        /// </summary>
        public static string PageNodeCannotBeNull {
            get {
                return ResourceManager.GetString("PageNodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Page Node&apos;s Display Name cannot be null or empty..
        /// </summary>
        public static string PageNodeDisplayNameCannotBeNull {
            get {
                return ResourceManager.GetString("PageNodeDisplayNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Page Node with id the id {0} exists..
        /// </summary>
        public static string PageNodeNotFound {
            get {
                return ResourceManager.GetString("PageNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Page Node&apos;s Url Name cannot be null or empty..
        /// </summary>
        public static string PageNodeUrlNameCannotBeNull {
            get {
                return ResourceManager.GetString("PageNodeUrlNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Page Node with the URL name {0} already exists in the Page with id {1}. Page Node URL name must be unique within a Page Node..
        /// </summary>
        public static string PageNodeUrlNameMustBeUniqueWithinPage {
            get {
                return ResourceManager.GetString("PageNodeUrlNameMustBeUniqueWithinPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Page Node with the URL name {0} already exists in the Section with id {1}. Page Node URL name must be unique within a Section Node..
        /// </summary>
        public static string PageNodeUrlNameMustBeUniqueWithinSection {
            get {
                return ResourceManager.GetString("PageNodeUrlNameMustBeUniqueWithinSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Template Action Name cannot be null or empty..
        /// </summary>
        public static string PageTemplateActionNameCannotBeNull {
            get {
                return ResourceManager.GetString("PageTemplateActionNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Template cannot be null..
        /// </summary>
        public static string PageTemplateCannotBeNull {
            get {
                return ResourceManager.GetString("PageTemplateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Template Model Name cannot be null or empty..
        /// </summary>
        public static string PageTemplateModelNameCannotBeNull {
            get {
                return ResourceManager.GetString("PageTemplateModelNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Page Template with the id {0} exists..
        /// </summary>
        public static string PageTemplateNotFound {
            get {
                return ResourceManager.GetString("PageTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Page Template with the id {0} exists for the Page Template with id {1}..
        /// </summary>
        public static string PageTemplateNotFoundForPageTemplate {
            get {
                return ResourceManager.GetString("PageTemplateNotFoundForPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Page Template with the id {0} exists for the Section Template with id {1}..
        /// </summary>
        public static string PageTemplateNotFoundForSectionTemplate {
            get {
                return ResourceManager.GetString("PageTemplateNotFoundForSectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered does not match the password we have for this email address..
        /// </summary>
        public static string PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Property with the id {0} exists..
        /// </summary>
        public static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Template cannot be null..
        /// </summary>
        public static string PropertyTemplateCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyTemplateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Property Template with the id {0} exists..
        /// </summary>
        public static string PropertyTemplateNotFound {
            get {
                return ResourceManager.GetString("PropertyTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Property Template with the id {0} exists for the Page Template with Id {1}..
        /// </summary>
        public static string PropertyTemplateNotFoundForPageTemplate {
            get {
                return ResourceManager.GetString("PropertyTemplateNotFoundForPageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Template Property Name cannot be null or empty..
        /// </summary>
        public static string PropertyTemplatePropertyNameCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyTemplatePropertyNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Node cannot be null..
        /// </summary>
        public static string SectionNodeCannotBeNull {
            get {
                return ResourceManager.GetString("SectionNodeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Section Node&apos;s Display Name cannot be null or empty..
        /// </summary>
        public static string SectionNodeDisplayNameCannotBeNull {
            get {
                return ResourceManager.GetString("SectionNodeDisplayNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Section Node with the Id {0} was not found..
        /// </summary>
        public static string SectionNodeNotFound {
            get {
                return ResourceManager.GetString("SectionNodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Section Node&apos;s Url Name cannot be null or empty..
        /// </summary>
        public static string SectionNodeUrlNameCannotBeNull {
            get {
                return ResourceManager.GetString("SectionNodeUrlNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Section Node with the URL name {0} alredy exists. Section Node URL names must be unique..
        /// </summary>
        public static string SectionNodeUrlNameMustBeUnique {
            get {
                return ResourceManager.GetString("SectionNodeUrlNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Section Node with the controller name {0} exists..
        /// </summary>
        public static string SectionNodeWithControllerNameNotFound {
            get {
                return ResourceManager.GetString("SectionNodeWithControllerNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Template cannot be null..
        /// </summary>
        public static string SectionTemplateCannotBeNull {
            get {
                return ResourceManager.GetString("SectionTemplateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Template Controller Name cannot be null or empty..
        /// </summary>
        public static string SectionTemplateControllerNameCannotBeNull {
            get {
                return ResourceManager.GetString("SectionTemplateControllerNameCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Section Template with the Controller Name {0} already exists..
        /// </summary>
        public static string SectionTemplateControllerNameMustBeUnique {
            get {
                return ResourceManager.GetString("SectionTemplateControllerNameMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No section template with the id {0} exists..
        /// </summary>
        public static string SectionTemplateNotFound {
            get {
                return ResourceManager.GetString("SectionTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username you entered does not exist..
        /// </summary>
        public static string UserNameNotFound {
            get {
                return ResourceManager.GetString("UserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User with the username {0} exists..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
